[package]
name = "barotropic_eq"
version = "0.1.0"
authors = ["asehgal"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
derive_more = "0.99.11"
